const { ccclass, property } = cc._decorator;

import { EventBus as bus } from "../../core/EventBus";
import { EventNames } from "../../core/events/EventNames";
import GameBoardController from "./GameBoardController";
import TileView from "../views/TileView";
import type { Board } from "../../core/board/Board";
import { loadBoardConfig } from "../../config/ConfigLoader";

@ccclass()
export default class MoveFlowController extends cc.Component {
  /** Parent node for new tile views */
  @property(cc.Node)
  tilesLayer!: cc.Node;

  /** Cached matrix of tile view components. Filled on load. */
  private tileViews!: TileView[][];
  /** Board model for reading final tile positions */
  private board!: Board;
  /** Reference to board controller so we can update its matrix */
  private boardCtrl!: GameBoardController;

  onLoad(): void {
    // Cache references to TileView matrix generated by GameBoardController
    this.boardCtrl = this.node.getComponent(GameBoardController)!;
    this.board = this.boardCtrl.getBoard();
    this.tileViews = this.boardCtrl.tileViews;

    // Listen for core events signalling board updates
    bus.on(EventNames.RemoveStarted, this.onRemove, this);
    bus.on(EventNames.FallDone, this.onFall, this);
  }

  /**
   * Plays scale + fade animation on removed tile views.
   * @param positions coordinates of tiles removed by the core
   */
  private onRemove(positions: cc.Vec2[]): void {
    console.log("onRemove called, this:", this);
    console.log("tileViews:", this.tileViews);
    positions.forEach((p) => {
      const view = this.tileViews[p.y][p.x];
      view.node.runAction(cc.spawn(cc.scaleTo(0.15, 0), cc.fadeOut(0.15)));
    });
  }

  /**
   * Animates tiles falling after removal.
   * @param dirtyCols column indices reported by the core's FallCommand
   *                  that contained holes and were shifted down.
   *                  Each tile view in these columns moves to its new Y.
   */
  private onFall(): void {
    // Build mapping from tile model instances to their views
    const map = new Map<unknown, TileView>();
    this.tileViews.forEach((row) =>
      row.forEach((v) => map.set((v as unknown as { tile: unknown }).tile, v)),
    );

    // Reconstruct matrix according to board state and move views
    const updated: (TileView | undefined)[][] = [];
    for (let r = 0; r < this.board.rows; r++) {
      updated[r] = new Array(this.board.cols);
    }

    this.board.forEach((p, t) => {
      const view = map.get(t);
      if (!view) return;
      const target = this.computePos(p.x, p.y);
      const dist = Math.abs(view.node.y - target.y);
      const dur = dist / 1400;
      view.node.runAction(cc.moveTo(dur, target.x, target.y));
      updated[p.y][p.x] = view;
    });

    this.tileViews = updated as TileView[][];
    this.boardCtrl.tileViews = this.tileViews;
  }

  /**
   * Compute tile position exactly like in GameBoardController.
   */
  private computePos(col: number, row: number): cc.Vec2 {
    const cfg = loadBoardConfig();
    const x = (col - this.board.cols / 2) * cfg.tileWidth;
    const y =
      (this.board.rows / 2 - row) * cfg.tileHeight -
      GameBoardController.VERTICAL_OFFSET;
    return cc.v2(x, y);
  }
}
