/**
 * Single source of truth for event names.
 * We use string constants because cc.EventTarget expects string names.
 */
export const EventNames = {
  GameStart: "GameStart",
  GameRestart: "GameRestart",
  GroupSelected: "GroupSelected",
  TilesRemoved: "TilesRemoved",
  MoveCompleted: "MoveCompleted",
  FillStarted: "FillStarted",
  FillDone: "FillDone",
  FallStarted: "FallStarted",
  FallDone: "FallDone",
  TurnsInit: "TurnsInit",
  TurnUsed: "TurnUsed",
  TurnEnded: "TurnEnded",
  OutOfTurns: "OutOfTurns",
  GameWon: "GameWon",
  GameLost: "GameLost",
  BoosterActivated: "BoosterActivated",
  BoosterConsumed: "BoosterConsumed",
  BoosterCancelled: "BoosterCancelled",
  BoostersSelected: "BoostersSelected",
  BoosterConfirmed: "BoosterConfirmed",
  BoosterTargetSelected: "BoosterTargetSelected",
  StateChanged: "StateChanged",
  GamePaused: "GamePaused",
  GameResumed: "GameResumed",
  AnimationStarted: "AnimationStarted",
  AnimationEnded: "AnimationEnded",
  AutoShuffle: "AutoShuffle",
  ShuffleLimitExceeded: "ShuffleLimitExceeded",
  ShuffleDone: "ShuffleDone",
  GroupFound: "GroupFound",
  SwapCancelled: "SwapCancelled",
  SwapDone: "SwapDone",
  RemoveStarted: "RemoveStarted",
  SuperTileCreated: "SuperTileCreated",
  SuperTilePlaced: "SuperTilePlaced",
  SuperTileActivated: "SuperTileActivated",
  /** Player pressed a tile (always). */
  TilePressed: "TilePressed",
  /** Tap is not considered a move (group < 2). */
  InvalidTap: "InvalidTap",
} as const;
