# Build and deploy web assets to GitHub Pages
name: Deploy # Human-friendly name for the workflow

on:
  workflow_dispatch: # Allow manual runs only

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a Linux runner
    steps:
      - name: Checkout source
        uses: actions/checkout@v4 # Fetch repository contents

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Provide Node for build step
        with:
          node-version: 20 # Utilize Node 20 LTS

      - name: Install dependencies
        run: npm ci # Install exact versions from package-lock.json

      - name: Ensure cocos CLI is available
        run: |
          if ! command -v cocoscli >/dev/null 2>&1; then
            npm install -g cocos-cli
          fi
          cocoscli --version # Output installed version for logging

      - name: Build web assets
        run: npm run build:web # Generate build/web-mobile

      - name: Prepare deployment folder
        run: |
          mkdir -p deploy # Create directory for deployment artifacts
          cp -r build/web-mobile/* deploy/ # Copy built web files

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Push files to gh-pages branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Authentication token
          publish_branch: gh-pages # Pages branch
          publish_dir: ./deploy # Directory to publish
          force_orphan: true # Create orphan branch for clean history
